Repository porn-vault/porn-vault, pull requests merged in 2020-12, with the labels that each got.

#1070 Fix/1068
  app/src/components/AppBar/ActorDetails.vue
  app/src/components/AppBar/StudioDetails.vue
  src/graphql/mutations/actor.ts
  src/graphql/mutations/label.ts
  src/graphql/mutations/studio.ts
  src/plugins/events/actor.ts
  src/plugins/events/studio.ts
  src/utils/misc.ts
  test/utils/fixtures/filter_invalid_aliases.fixtures.ts
  test/utils/misc.spec.ts
Labels: enhancement, fix

#1053 optimize `attachToScenes` (0.26)
  .github/workflows/build-server.yml
  app/src/views/ActorDetails.vue
  app/src/views/StudioDetails.vue
  config.example.json
  docker/run.sh
  package-lock.json
  package.json
  src/config/default.ts
  src/config/schema.ts
  src/graphql/mutations/actor.ts
  src/graphql/mutations/image.ts
  src/graphql/mutations/studio.ts
  src/graphql/schema/actor.ts
  src/graphql/schema/studio.ts
  src/matching/wordMatcher.ts
  src/plugins/events/movie.ts
  src/plugins/events/scene.ts
  src/plugins/events/studio.ts
  src/search/index.ts
  src/search/internal/constants.ts
  src/search/scene.ts
  src/types/actor.ts
  src/types/image.ts
  src/types/label.ts
  src/types/scene.ts
  src/types/studio.ts
  src/utils/fs/async.ts
  src/utils/misc.ts
  src/utils/string.ts
  test/graphql/mutations/actor.spec.ts
  test/graphql/mutations/studio.spec.ts
  test/testServer.ts
  test/types/actor.spec.ts
  test/types/studio.spec.ts
  test/utils/fixtures/get_extension.fixture.ts
  test/utils/fixtures/is_array_eq.fixtures.ts
  test/utils/fixtures/remove_extension.fixture.ts
  test/utils/misc.spec.ts
  test/utils/string.spec.ts
Labels: optimization, refactor

#1099 fix: plugins could not use $zod
  src/plugins/index.ts
Labels: fix

#1101 fix(ActorDetails): refresh linked data after attaching
  app/src/views/ActorDetails.vue
Labels: fix

#1103 rewrite build scripts with gulp
  .github/workflows/build-app.yml
  .github/workflows/build-server.yml
  .github/workflows/release.yml
  docker/Dockerfile.alpine
  docker/Dockerfile.debian
  gulpfile.ts
  package-lock.json
  package.json
Labels: refactor, repo

#1119 gulpfile: handle exec error, check assets/version.json
  gulpfile.ts
Labels: refactor, repo
