Repository porn-vault/porn-vault, pull requests merged in 2020-11, with the labels that each got.

#992 Fix scene selector: update scenes
  app/src/components/SceneSelector.vue
  app/src/views/Images.vue
Labels: fix

#963 Feature: scene import: configurable extraction
  app/src/components/SceneSelector.vue
  app/src/views/Images.vue
  config.json.example
  doc/config.md
  package-lock.json
  package.json
  src/config/default.ts
  src/config/schema.ts
  src/graphql/mutations/movie.ts
  src/types/scene.ts
  test/fixtures/files/dynamicTestFiles.ts
  test/testServer.ts
  test/types/scene.spec.ts
Labels: new feature

#996 Feature: automatically generate valid config schema from user's config, no exit on config reload
  .gitignore
  src/binaries/gianna.ts
  src/config/default.ts
  src/config/index.ts
  src/config/validate.ts
  src/database/index.ts
  src/index.ts
  src/plugins/validate.ts
  src/setup.ts
  src/utils/misc.ts
  src/utils/types.ts
  test/config/index.spec.ts
  test/plugins/initPluginFixtures.ts
  test/util/fixtures/mergeMissingProperties.fixtures.ts
  test/util/fixtures/removeUnknownProperties.fixtures.ts
  test/util/mergeMissingProperties.spec.ts
  test/util/removeUnknownProperties.spec.ts
Labels: new feature

#998 refactor routing
  app/src/components/ActorGrid.vue
  app/src/components/ActorSelector.vue
  app/src/components/AppBar/SceneDetails.vue
  app/src/components/Cards/Actor.vue
  app/src/components/Collabs.vue
  app/src/components/ImageCard.vue
  app/src/components/Lightbox.vue
  app/src/components/MarkerCard.vue
  app/src/components/MovieCard.vue
  app/src/components/SceneSelector.vue
  app/src/components/StudioCard.vue
  app/src/components/StudioSelector.vue
  app/src/mixins/scene.ts
  app/src/router/index.ts
  app/src/views/ActorDetails.vue
  app/src/views/Actors.vue
  app/src/views/Graph.vue
  app/src/views/MovieDetails.vue
  app/src/views/SceneDetails.vue
  app/src/views/Scenes.vue
  app/src/views/StudioDetails.vue
  assets/version.json
  package.json
  src/database/internal/index.ts
  src/dvd_renderer.ts
  src/routers/media.ts
  src/routers/scan.ts
  src/routers/static.ts
  src/search/internal/index.ts
  src/server.ts
Labels: refactor

#1001 refactor(Scenes): allow unlimited duration
  app/src/views/Scenes.vue
Labels: fix, refactor

#1003 Refactor: use single docker volume
  .gitignore
  config.example.json
  doc/docker.md
  docker/Dockerfile.alpine
  docker/Dockerfile.debian
  docker/run.sh
  src/backup.ts
  src/binaries/gianna.ts
  src/binaries/izzy.ts
  src/config/index.ts
  src/setup.ts
  src/utils/misc.ts
Labels: refactor

#1016 Clear label selection button
  app/src/components/LabelSelector.vue
  app/src/components/Lightbox.vue
  app/src/views/ActorDetails.vue
  app/src/views/Actors.vue
  app/src/views/SceneDetails.vue
  app/src/views/Scenes.vue
  app/src/views/StudioDetails.vue
Labels: enhancement, new feature

#1026 fix(SceneDetails): don't trigger with kb modifiers
  app/src/views/SceneDetails.vue
Labels: fix

#1022 add GET scan/folders & add to scan widget
  app/src/components/HomeWidgets/Scan.vue
  src/routers/scan.ts
Labels: enhancement

#1002 Feature: attach actor/studio labels more often, can be configured
  config.example.json
  doc/config.md
  src/config/default.ts
  src/config/schema.ts
  src/graphql/mutations/actor.ts
  src/graphql/mutations/image.ts
  src/graphql/mutations/scene.ts
  src/graphql/mutations/studio.ts
  src/graphql/resolvers/search/marker.ts
  src/graphql/schema/studio.ts
  src/plugins/events/actor.ts
  src/plugins/events/movie.ts
  src/plugins/events/scene.ts
  src/plugins/events/studio.ts
  src/types/actor.ts
  src/types/scene.ts
  src/types/studio.ts
  test/fixtures/files/dynamicTestFiles.ts
  test/graphql/mutations/actor.spec.ts
  test/graphql/mutations/image.spec.ts
  test/graphql/mutations/scene.spec.ts
  test/graphql/mutations/studio.spec.ts
  test/plugins/events/actor.spec.ts
  test/plugins/events/movie.spec.ts
  test/plugins/events/scene.spec.ts
  test/plugins/events/studio.spec.ts
  test/plugins/fixtures/actor_plugin.fixture.js
  test/plugins/fixtures/actor_plugin.fixture.ts
  test/plugins/fixtures/scene_plugin.fixture.js
  test/plugins/fixtures/scene_plugin.fixture.ts
  test/plugins/fixtures/studio_plugin.fixture.js
  test/plugins/fixtures/studio_plugin.fixture.ts
  test/types/actor.spec.ts
  test/types/scene.spec.ts
  test/types/studio.spec.ts
Labels: fix, new feature

#997 refactor index build: simplify, log time
  src/search/actor.ts
  src/search/image.ts
  src/search/internal/buildIndex.ts
  src/search/marker.ts
  src/search/movie.ts
  src/search/scene.ts
  src/search/studio.ts
Labels: refactor

#1032 Feature: add new "word" matcher in config
  config.example.json
  doc/config.md
  doc/matcher.md
  src/app.ts
  src/backup.ts
  src/binaries/gianna.ts
  src/binaries/izzy.ts
  src/config/default.ts
  src/config/index.ts
  src/config/schema.ts
  src/database/index.ts
  src/extractor.ts
  src/graphql/mutations/actor.ts
  src/graphql/mutations/image.ts
  src/graphql/mutations/label.ts
  src/graphql/mutations/studio.ts
  src/index.ts
  src/matching/matcher.ts
  src/matching/stringMatcher.ts
  src/matching/wordMatcher.ts
  src/plugins/events/actor.ts
  src/plugins/events/movie.ts
  src/plugins/events/scene.ts
  src/plugins/events/studio.ts
  src/plugins/index.ts
  src/queue/check.ts
  src/setup.ts
  src/types/actor.ts
  src/types/marker.ts
  src/types/scene.ts
  src/types/studio.ts
  src/utils/misc.ts
  src/utils/path.ts
  src/utils/string.ts
  test/config/index.spec.ts
  test/config/schema.spec.ts
  test/fixtures/matching_actor.fixture.ts
  test/fixtures/matching_label.fixture.ts
  test/fixtures/strip_string.fixture.ts
  test/matching/fixtures/matching_actor.fixture.ts
  test/matching/fixtures/matching_label.fixture.ts
  test/matching/fixtures/string_filter.fixture.ts
  test/matching/fixtures/strip_string.fixture.ts
  test/matching/fixtures/wordMatcher.fixtures.ts
  test/matching/matcher.spec.ts
  test/matching/stringMatcher.spec.ts
  test/matching/wordMatcher.spec.ts
  test/string.spec.ts
  test/url_ext.spec.ts
  test/util/fixtures/mergeMissingProperties.fixtures.ts
  test/util/mergeMissingProperties.spec.ts
  test/utils/fixtures/misc.fixtures.ts
  test/utils/fixtures/remove_extension.fixture.ts
  test/utils/fixtures/url_ext.fixture.ts
  test/utils/misc.spec.ts
  test/utils/string.spec.ts
  test/utils/url_ext.spec.ts
  tsconfig.json
Labels: enhancement, fix, new feature

#1033 Optimize setLabels, setScenes, setActors
  src/types/image.ts
  src/types/label.ts
  src/types/movie.ts
  src/types/scene.ts
  src/utils/misc.ts
  test/utils/fixtures/array_diff.fixtures.ts
  test/utils/fixtures/generate_timestamps.fixtures.ts
  test/utils/misc.spec.ts
Labels: optimization

#1038 adjust $walk
  src/utils/fs/async.ts
  test/fixtures/files/.hidden/image100.jpg
  test/walk.spec.ts
Labels: refactor

#1041 fix: scene & actor plugins can't be run from web ui
  app/src/views/ActorDetails.vue
  app/src/views/SceneDetails.vue
  app/src/views/StudioDetails.vue
  src/graphql/mutations/studio.ts
  src/graphql/schema/studio.ts
Labels: fix, high priority

#1051 fix docker: do not copy example config if config.yaml exists
  docker/run.sh
Labels: docker, fix

#1054 fix: cannot set actor alt thumbnail
  src/graphql/mutations/image.ts
  src/matching/wordMatcher.ts
  src/utils/fs/async.ts
  src/utils/string.ts
  test/utils/fixtures/get_extension.fixture.ts
  test/utils/fixtures/remove_extension.fixture.ts
  test/utils/string.spec.ts
Labels: fix

#1055 optimize `attachToScenes` (0.25)
  .github/workflows/build-server.yml
  app/src/views/ActorDetails.vue
  app/src/views/StudioDetails.vue
  config.example.json
  package.json
  src/config/default.ts
  src/config/schema.ts
  src/graphql/mutations/actor.ts
  src/graphql/mutations/studio.ts
  src/graphql/schema/actor.ts
  src/graphql/schema/studio.ts
  src/plugins/events/movie.ts
  src/plugins/events/scene.ts
  src/plugins/events/studio.ts
  src/types/actor.ts
  src/types/label.ts
  src/types/scene.ts
  src/types/studio.ts
  src/utils/misc.ts
  test/graphql/mutations/actor.spec.ts
  test/graphql/mutations/studio.spec.ts
  test/testServer.ts
  test/types/actor.spec.ts
  test/types/studio.spec.ts
  test/utils/fixtures/is_array_eq.fixtures.ts
  test/utils/misc.spec.ts
Labels: optimization, refactor
