Repository porn-vault/porn-vault, pull requests merged in 2020-09, with the labels that each got.

#779 add scan card
  app/src/components/HomeWidgets/QueueInfo.vue
  app/src/components/HomeWidgets/Scan.vue
  app/src/components/HomeWidgets/Stats.vue
  app/src/views/Home.vue
  src/scanner.ts
  src/server.ts
Labels: enhancement

#776 added bar in player to change volume
  app/src/components/VideoPlayer.vue
Labels: enhancement

#795 Implement new config format & remove old backwards compatibility
  .gitignore
  Dockerfile
  app/src/components/HomeWidgets/ActorLabelUsage.vue
  app/src/components/HomeWidgets/RemainingTime.vue
  app/src/components/HomeWidgets/Scan.vue
  app/src/components/HomeWidgets/SceneLabelUsage.vue
  app/src/views/About.vue
  app/src/views/Home.vue
  config.json.example
  config.yaml.example
  doc/config.md
  doc/pipe_plugins.md
  doc/plugin_development.md
  doc/plugins_intro.md
  package-lock.json
  package.json
  run.sh
  src/apollo.ts
  src/compat/index.ts
  src/config/default.ts
  src/config/index.ts
  src/config/schema.ts
  src/config/validate.ts
  src/database/index.ts
  src/database/internal/index.ts
  src/dvd_renderer.ts
  src/gianna.ts
  src/graphql/mutations/actor.ts
  src/graphql/mutations/image.ts
  src/graphql/mutations/scene.ts
  src/import/index.ts
  src/index.ts
  src/integrity.ts
  src/izzy.ts
  src/logger.ts
  src/password.ts
  src/plugin_events/actor.ts
  src/plugin_events/movie.ts
  src/plugin_events/scene.ts
  src/plugins/index.ts
  src/plugins/validate.ts
  src/queue/check.ts
  src/queue/processing.ts
  src/queue_loop.ts
  src/search/internal/index.ts
  src/server.ts
  src/setup.ts
  src/types/actor.ts
  src/types/image.ts
  src/types/label.ts
  src/types/marker.ts
  src/types/movie.ts
  src/types/scene.ts
  src/types/studio.ts
  src/types/utility.ts
  test/config/index.spec.ts
  test/config/schema.fixture.ts
  test/config/schema.spec.ts
Labels: enhancement

#820 refactor(getById): use getBulk when possible
  src/graphql/mutations/image.ts
  src/graphql/mutations/scene.ts
  src/types/actor.ts
  src/types/custom_field.ts
  src/types/image.ts
  src/types/label.ts
  src/types/marker.ts
  src/types/movie.ts
  src/types/scene.ts
  src/types/studio.ts
Labels: optimization

#789 Enhancement(SceneDetails): custom controls in fullscreen, add kb shortcuts
  app/src/components/VideoPlayer.vue
  app/src/views/SceneDetails.vue
Labels: enhancement

#790 Repo: rename release zips
  .github/workflows/release.yml
  package.json
Labels: repo

#826 Fix: video player white background on tall screens
  app/src/components/VideoPlayer.vue
  package-lock.json
Labels: fix

#827 Update docs, add config lint message
  doc/config.md
  doc/docker.md
  doc/guides.md
  src/config/index.ts
Labels: documentation
