Repository porn-vault/porn-vault, pull requests merged in 2020-10, with the labels that each got.

#829 refactor(Images): ctrl/shift selection
  app/src/components/ImageCard.vue
  app/src/views/Images.vue
Labels: new feature

#875 Enhancement(SceneCard): add watched chip
  app/src/components/SceneCard.vue
Labels: enhancement

#874 remove rimraf & mkdirp, closes #817
  package-lock.json
  package.json
  src/database/index.ts
  src/types/scene.ts
  src/utils/fs/async.ts
  test/util.ts
  test/walk.spec.ts
Labels: optimization

#824 (refactor) Search query format
  app/src/views/ActorDetails.vue
  app/src/views/Actors.vue
  app/src/views/Images.vue
  app/src/views/Markers.vue
  app/src/views/Movies.vue
  app/src/views/SceneDetails.vue
  app/src/views/Scenes.vue
  app/src/views/StudioDetails.vue
  app/src/views/Studios.vue
  src/graphql/resolvers/query.ts
  src/graphql/resolvers/search/actor.ts
  src/graphql/resolvers/search/image.ts
  src/graphql/resolvers/search/marker.ts
  src/graphql/resolvers/search/movie.ts
  src/graphql/resolvers/search/scene.ts
  src/graphql/resolvers/search/studio.ts
  src/graphql/schema/actor.ts
  src/graphql/schema/image.ts
  src/graphql/schema/marker.ts
  src/graphql/schema/movie.ts
  src/graphql/schema/scene.ts
  src/graphql/schema/studio.ts
  src/query_extractor.ts
  src/search/actor.ts
  src/search/common.ts
  src/search/image.ts
  src/search/internal/index.ts
  src/search/marker.ts
  src/search/movie.ts
  src/search/scene.ts
  src/search/studio.ts
  src/server.ts
  src/types/actor.ts
Labels: refactor

#900 fix #669
  src/types/image.ts
  src/types/movie.ts
  src/types/movie_scene.ts
  src/types/scene.ts
Labels: fix

#901 fix #600
  src/graphql/mutations/actor.ts
  src/graphql/mutations/studio.ts
  src/plugins/events/scene.ts
  src/types/actor.ts
  src/types/studio.ts
Labels: fix

#906 fix processing queue behavior
  src/queue_router.ts
Labels: fix

#909 fix(Markers): update refresh on sort change
  app/src/views/Markers.vue
Labels: fix

#908 fix(ImageCard): use click event, search query format
  app/src/components/ActorSelector.vue
  app/src/components/SceneSelector.vue
  app/src/components/StudioSelector.vue
  app/src/views/ActorDetails.vue
  app/src/views/MovieDetails.vue
  app/src/views/SceneDetails.vue
Labels: fix, high priority

#823 refactor(scene): use seconds for timestamps in thumbnail generation
  src/types/scene.ts
  src/utils/misc.ts
  test/utils/misc.fixtures.ts
  test/utils/misc.spec.ts
Labels: optimization, refactor

#911 Feat: handle typescript plugins
  package-lock.json
  package.json
  src/plugins/index.ts
  test/config/index.spec.ts
  test/plugins/events/actor.spec.ts
  test/plugins/events/movie.spec.ts
  test/plugins/events/scene.spec.ts
  test/plugins/fixtures/actor_plugin.fixture.js
  test/plugins/fixtures/actor_plugin.fixture.ts
  test/plugins/fixtures/config.test.fixture_js.json
  test/plugins/fixtures/config.test.fixture_ts.json
  test/plugins/fixtures/movie_plugin.fixture.js
  test/plugins/fixtures/movie_plugin.fixture.ts
  test/plugins/fixtures/scene_plugin.fixture.js
  test/plugins/fixtures/scene_plugin.fixture.ts
  test/plugins/initPluginFixtures.ts
Labels: new feature

#876 Feature: studio plugin events
  app/src/views/StudioDetails.vue
  config.json.example
  src/config/default.ts
  src/config/schema.ts
  src/graphql/mutations/studio.ts
  src/graphql/resolvers/studio.ts
  src/graphql/schema/studio.ts
  src/import/create.ts
  src/import/schemas/studio.ts
  src/import/types.ts
  src/import/verify.ts
  src/plugins/events/studio.ts
  src/types/studio.ts
  test/plugins/events/scene.spec.ts
  test/plugins/events/studio.spec.ts
  test/plugins/fixtures/config.test.fixture_js.json
  test/plugins/fixtures/config.test.fixture_ts.json
  test/plugins/fixtures/scene_plugin.fixture.js
  test/plugins/fixtures/studio_plugin.fixture.js
  test/plugins/fixtures/studio_plugin.fixture.ts
Labels: new feature

#926 remove bulk import
  config.json.example
  doc/guides.md
  doc/import.md
  src/config/default.ts
  src/config/schema.ts
  src/import/create.ts
  src/import/index.ts
  src/import/schemas/actor.ts
  src/import/schemas/common.ts
  src/import/schemas/custom_field.ts
  src/import/schemas/label.ts
  src/import/schemas/marker.ts
  src/import/schemas/movie.ts
  src/import/schemas/scene.ts
  src/import/schemas/studio.ts
  src/import/types.ts
  src/import/validate.ts
  src/import/verify.ts
  src/server.ts
  test/plugins/fixtures/config.test.fixture_js.json
  test/plugins/fixtures/config.test.fixture_ts.json
Labels: regression

#962 refactor config: clean
  src/config/index.ts
  src/config/validate.ts
  src/index.ts
  src/utils/logger.ts
  test/config/index.spec.ts
  test/plugins/fixtures/config.test.fixture_js.json
  test/plugins/fixtures/config.test.fixture_ts.json
  test/plugins/initPluginFixtures.ts
Labels: refactor

#980 Fix: prevent studio plugin circular references
  src/plugins/events/studio.ts
  test/plugins/events/studio.spec.ts
  test/plugins/fixtures/studio/recursive.fixture.js
  test/testServer.ts
Labels: fix
