Repository porn-vault/porn-vault, pull requests merged in 2020-06, with the labels that each got.

#563 Refactor config: facilitate testing, write tests
  .gitignore
  package-lock.json
  package.json
  src/config/index.ts
  src/index.ts
  src/logger.ts
  src/setup.ts
  test/config/index.spec.ts
Labels: enhancement

#588 Fix walk: permission denied crashing app
  package-lock.json
  package.json
  src/fs/async.ts
  src/logger.ts
  test/init.ts
  test/util.ts
  test/walk.spec.ts
Labels: fix

#587 Toggle option for scene preview in SceneCard
  app/src/components/SceneCard.vue
  app/src/store/context.ts
  app/src/views/About.vue
Labels: enhancement, new feature
