Repository porn-vault/porn-vault, pull requests merged in 2021-01, with the labels that each got.

#1146 enable actor custom field filter
  app/src/components/CustomFieldFilter.vue
  app/src/views/Actors.vue
  src/config/default.ts
  src/graphql/resolvers.ts
  src/graphql/resolvers/actor.ts
  src/graphql/schema/actor.ts
  src/graphql/schema/index.ts
  src/matching/stringMatcher.ts
  src/search/actor.ts
  src/search/common.ts
  src/search/image.ts
  src/search/marker.ts
  src/search/movie.ts
  src/search/scene.ts
  src/types/actor.ts
  src/types/studio.ts
  test/config/index.spec.ts
  test/matching/fixtures/matching_label.fixture.ts
  test/matching/stringMatcher.spec.ts
  test/types/studio.spec.ts
Labels: enhancement, new feature

#1126 use transparent broken.png
  app/src/components/ActorGrid.vue
  app/src/components/Cards/Actor.vue
  app/src/components/Cards/Marker.vue
  app/src/components/Cards/Movie.vue
  app/src/components/Cards/Studio.vue
  app/src/components/Collabs.vue
  app/src/mixins/scene.ts
  app/src/views/ActorDetails.vue
  app/src/views/SceneDetails.vue
  app/src/views/StudioDetails.vue
  assets/broken.png
  src/app.ts
  src/data/broken_image.ts
  src/routers/media.ts
Labels: enhancement, refactor

#1131 add a refresh interval on home stats card
  app/src/components/HomeWidgets/Stats.vue
Labels: enhancement

#1127 feat: run ffprobe from ui
  .gitignore
  app/src/views/SceneDetails.vue
  src/app.ts
  src/graphql/mutations/scene.ts
  src/graphql/schema/scene.ts
  src/queue_router.ts
  src/types/scene.ts
  test/fixtures/files/dynamic/.gitkeep
  test/fixtures/files/dynamicTestFiles.ts
  test/graphql/mutations/actor.spec.ts
  test/graphql/mutations/scene.spec.ts
  test/graphql/mutations/studio.spec.ts
  test/types/actor.spec.ts
  test/types/scene.spec.ts
  test/types/studio.spec.ts
Labels: new feature

#1181 Fix: match custom field with legacy matcher
  src/extractor.ts
Labels: fix

#1177 docs, more logging options, fix writing merged config
  config.example.json
  doc/apply_labels.md
  doc/build_from_source.md
  doc/config.md
  doc/docker.md
  doc/guides.md
  doc/logging.md
  doc/startup_options.md
  package.json
  src/config/default.ts
  src/config/index.ts
  src/config/schema.ts
  src/graphql/mutations/scene.ts
  src/routers/scan.ts
  src/scanner.ts
  src/server.ts
  src/utils/logger.ts
  src/utils/misc.ts
  test/config/index.spec.ts
Labels: documentation, enhancement, fix

#1182 fix calculateScore, retrieve score on actor details page
  app/src/views/ActorDetails.vue
  src/types/actor.ts
Labels: fix

#1176 Fix crash when deleting scenes, optimize db usage
  app/src/views/Scenes.vue
  src/binaries/izzy.ts
  src/database/index.ts
  src/graphql/mutations/label.ts
  src/graphql/mutations/scene.ts
  src/graphql/mutations/studio.ts
  src/graphql/resolvers/query.ts
  src/middlewares/password.ts
  src/plugins/events/studio.ts
  src/search/actor.ts
  src/search/scene.ts
  src/server.ts
  src/types/actor.ts
  src/types/common.ts
  src/types/image.ts
  src/types/marker.ts
  src/types/movie.ts
  src/types/scene.ts
  src/types/studio.ts
Labels: fix, optimization
