Repository porn-vault/porn-vault, pull requests merged in 2021-03, with the labels that each got.

#1254 VideoPlayer: various features and improvements, fix preview offset
  app/package-lock.json
  app/package.json
  app/src/components/MarkerItem.vue
  app/src/components/VideoPlayer.vue
  app/src/views/SceneDetails.vue
Labels: fix, refactor, ux

#1253 add initial 'data' to plugin context
  src/plugins/events/actor.ts
  src/plugins/events/movie.ts
  src/plugins/events/scene.ts
  src/plugins/events/studio.ts
Labels: enhancement

#1319 fix(createFileTransport): deterministic auditFile
  nodemon.json
  src/utils/logger.ts
Labels: fix

#1318 Fix scene thumbnail/screenshot name conflict
  src/queue_loop.ts
  src/types/scene.ts
Labels: fix

#1317 AddLabel: only match created label
  src/extractor.ts
  src/graphql/mutations/label.ts
  src/types/actor.ts
  src/types/studio.ts
  test/graphql/mutations/label.spec.ts
Labels: optimization

#1341 Fix: could not delete movie
  src/search/actor.ts
  src/search/image.ts
  src/search/marker.ts
  src/search/movie.ts
  src/search/scene.ts
  src/search/studio.ts
  test/graphql/mutations/movie.spec.ts
Labels: fix

#1360 Feat: log apollo errors
  src/middlewares/apollo.ts
Labels: enhancement
