Repository porn-vault/porn-vault, pull requests merged in 2021-04, with the labels that each got.

#1368 fix: processing would fail when using a self-signed certificate
  src/queue_loop.ts
Labels: fix

#1383 Update docker.md
  doc/docker.md
Labels: docker, documentation

#1380 Feat: show aliases in actor, studio selector
  app/src/components/ActorSelector.vue
  app/src/components/StudioSelector.vue
Labels: enhancement, ux

#1369 fix: app bar would disappear when navigating backwards
  app/src/App.vue
  app/src/router/index.ts
Labels: fix

#1384 Search: don't add default filter values to url
  app/src/util/searchState.ts
  app/src/views/Actors.vue
  app/src/views/Images.vue
  app/src/views/Movies.vue
  app/src/views/Scenes.vue
  app/src/views/Studios.vue
Labels: enhancement, refactor, ux

#822 Markers
  app/src/App.vue
  app/src/components/Cards/Marker.vue
  app/src/components/CustomFieldSelector.vue
  app/src/components/LabelSelector.vue
  app/src/components/MarkerItem.vue
  app/src/views/Markers.vue
  app/src/views/SceneDetails.vue
  src/graphql/mutations/marker.ts
  src/graphql/resolvers/marker.ts
  src/graphql/schema/marker.ts
  src/plugins/events/actor.ts
  src/plugins/events/scene.ts
  src/plugins/events/studio.ts
  src/search/marker.ts
  src/types/marker.ts
Labels: api, enhancement, new feature

#927 Settings: split into subpages, auto theme, customize seek duration
  app/src/App.vue
  app/src/components/SettingsWrapper.vue
  app/src/router/index.ts
  app/src/store/context.ts
  app/src/views/About.vue
  app/src/views/SceneDetails.vue
  app/src/views/Settings/Metadata.vue
  app/src/views/Settings/Settings.vue
  app/src/views/Settings/UI.vue
Labels: enhancement, styling/css, ux

#1424 Plugin meta
  doc/plugin_development.md
  package-lock.json
  package.json
  src/config/validate.ts
  src/plugins/context.ts
  src/plugins/index.ts
  src/plugins/register.ts
  src/plugins/validate.ts
  src/startup.ts
Labels: enhancement, plugins

#1378 Fix: preview would show two images at once ; show studio, movie name fallback in details page
  app/src/components/VideoPlayer.vue
  app/src/types/scene.ts
  app/src/views/MovieDetails.vue
  app/src/views/SceneDetails.vue
  src/graphql/resolvers/scene.ts
  src/queue_loop.ts
Labels: fix
