Repository porn-vault/porn-vault, pull requests merged in 2021-05, with the labels that each got.

#1431 fix(VideoPlayer): menu not showing in fullscreen
  app/src/components/VideoPlayer.vue
Labels: fix, ux

#1432 Add 3D dvd renderer to details page, fix normal view layout
  app/package-lock.json
  app/package.json
  app/src/App.vue
  app/src/components/DVDRenderer.vue
  app/src/fragments/movie.ts
  app/src/router/index.ts
  app/src/store/context.ts
  app/src/store/movie.ts
  app/src/types/movie.ts
  app/src/views/MovieDVD.vue
  app/src/views/MovieDetails.vue
  app/src/views/Settings/UI.vue
  app/tsconfig.json
  assets/OrbitControls.js
  assets/three.min.js
  src/dvd_renderer.ts
  src/graphql/resolvers/movie.ts
  src/plugins/events/movie.ts
  src/routers/static.ts
  src/static.ts
  src/types/image.ts
  views/dvd-renderer.html
Labels: enhancement, ux

#1436 Add h264 transcode option with hardware acceleration support
  .eslintrc.js
  app/src/fragments/scene.ts
  app/src/views/SceneDetails.vue
  config.example.json
  doc/config.md
  doc/docker.md
  docker/Dockerfile.alpine
  docker/Dockerfile.debian
  docker/run.sh
  src/app.ts
  src/config/default.ts
  src/config/schema.ts
  src/database/index.ts
  src/ffmpeg/ffprobe.ts
  src/graphql/resolvers/scene.ts
  src/graphql/schema/scene.ts
  src/routers/scene.ts
  src/transcode/copyMp4.ts
  src/transcode/mp4.ts
  src/transcode/transcoder.ts
  src/transcode/webm.ts
  src/types/scene.ts
  test/fixtures/files/dynamicTestFiles.ts
  test/transcode/copyMp4.spec.ts
  test/transcode/mp4.spec.ts
  test/transcode/webm.spec.ts
Labels: docker, new feature

#1443 close #1433
  app/src/components/LabelSelector.vue
  app/src/components/Lightbox.vue
  app/src/views/ActorDetails.vue
  app/src/views/SceneDetails.vue
  app/src/views/StudioDetails.vue
Labels: fix, refactor

#1444 fix(DVDRenderer): incorrect style
  app/src/components/DVDRenderer.vue
  app/src/views/MovieDVD.vue
  app/src/views/MovieDetails.vue
Labels: fix, ux

#1452 fix(server): only backup before loading db
  src/server.ts
Labels: fix

#1463 Fix VideoPlayer: touch problems
  app/src/components/VideoPlayer.vue
Labels: fix, high priority, ux

#1451 fix(mp4 transcode): only apply bitrate for amf windows
  src/transcode/mp4.ts
  test/testServer.ts
  test/transcode/mp4.spec.ts
Labels: fix, windows

#1466 Fix video player toggling play state, fit option display condition
  app/src/components/VideoPlayer.vue
  docs/404.html
  docs/assets/js/app.f622f644.js
  docs/guides/apply-labels.html
  docs/guides/build-from-source.html
  docs/guides/config.html
  docs/guides/docker.html
  docs/guides/env.html
  docs/guides/getting-started.html
  docs/guides/https.html
  docs/guides/logging.html
  docs/guides/matcher.html
  docs/guides/pipe-plugins.html
  docs/guides/plugin-development.html
  docs/guides/plugins-intro.html
  docs/guides/startup-options.html
  docs/guides/systemd.html
  docs/index.html
  src/plugins/index.ts
Labels: fix, high priority

#1497 Various VideoPlayer fixes
  app/src/components/VideoPlayer.vue
Labels: enhancement, fix, styling/css, ux

#1498 Add cuda transcode config
  page/docs/guides/config.md
  src/config/schema.ts
  src/transcode/mp4.ts
Labels: documentation, enhancement

#1500 Fix studio matching: use last appearance
  src/extractor.ts
  src/matching/matcher.ts
  src/matching/stringMatcher.ts
  src/matching/wordMatcher.ts
  test/matching/studio.spec.ts
Labels: fix

#1510 Fix mp4 transcode: handle adts aac
  src/transcode/mp4.ts
Labels: fix
